import { useState } from "react";
import GoogleForm from "../ui/GoogleForm";

const CSS = `
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0;}
body{background:#0A0A0A;color:#fff;font-family:'Inter',sans-serif;overflow-x:hidden;}
:root{--g:#C9A84C;--g2:#E0B85A;--cr:#F5F0E8;--b1:#0A0A0A;--b2:#0E0E0E;--b3:#111111;--bd:rgba(201,168,76,.18);--bds:rgba(201,168,76,.07);}
.ed{width:100%;padding:64px 7vw;position:relative;}.ed.b1{background:var(--b1);}.ed.b2{background:var(--b2);}.ed.b3{background:var(--b3);}.ed+.ed{border-top:1px solid var(--bd);}
.inn{max-width:1200px;margin:0 auto;}
.tc{display:flex;align-items:center;gap:64px;}.tc .col{flex:1;min-width:0;}.tc .coli{flex:1;display:flex;justify-content:center;align-items:center;}
.ibox{width:100%;max-width:510px;aspect-ratio:4/3;border-radius:16px;border:none;background:transparent;overflow:hidden;}.ibox img{width:100%;height:100%;object-fit:contain;border-radius:16px;display:block;}
.hg{font-family:'Libre Baskerville',serif;font-size:clamp(1.7rem,2.5vw,2.5rem);font-weight:700;color:var(--g);line-height:1.27;letter-spacing:-.01em;margin-bottom:24px;}
.hg-sm{font-size:clamp(1.25rem,1.75vw,1.8rem);}.hg-lg{font-size:clamp(1.9rem,3vw,2.9rem);}.hg-c{text-align:center;}
.sub{font-family:'Inter',sans-serif;font-size:clamp(.88rem,1.05vw,1rem);color:var(--cr);line-height:1.73;opacity:.88;}
.gb{width:48px;height:3px;background:var(--g);border-radius:2px;margin-bottom:20px;}.gb-c{margin:0 auto 20px;}
.bl{list-style:none;display:flex;flex-direction:column;gap:12px;margin-bottom:28px;}.bi{display:flex;align-items:flex-start;gap:11px;font-family:'Inter',sans-serif;font-size:clamp(.86rem,1vw,.98rem);color:var(--cr);line-height:1.68;}.bi .tk{flex-shrink:0;margin-top:2px;}
.br{display:flex;flex-wrap:wrap;gap:14px;}.bg-btn{background:var(--g);color:#0A0A0A;font-family:'Inter',sans-serif;font-weight:700;font-size:.9rem;padding:13px 30px;border:none;border-radius:6px;cursor:pointer;letter-spacing:.03em;transition:all .25s;white-space:nowrap;}.bg-btn:hover{background:var(--g2);transform:translateY(-2px);box-shadow:0 8px 24px rgba(201,168,76,.32);}
.slo{position:relative;overflow:hidden;padding:10px 0;}.slo::before,.slo::after{content:'';position:absolute;top:0;bottom:0;width:160px;z-index:2;pointer-events:none;}
.slo.fb2::before{left:0;background:linear-gradient(to right,#0E0E0E 25%,transparent);}.slo.fb2::after{right:0;background:linear-gradient(to left,#0E0E0E 25%,transparent);}
.slo.fb3::before{left:0;background:linear-gradient(to right,#111111 25%,transparent);}.slo.fb3::after{right:0;background:linear-gradient(to left,#111111 25%,transparent);}
.s-track{display:flex;gap:22px;width:max-content;animation:mq 24s linear infinite;}.s-track.rv{animation-direction:reverse;animation-duration:19s;}.s-track:hover{animation-play-state:paused;}
@keyframes mq{from{transform:translateX(0);}to{transform:translateX(-50%);}}
.icl{width:140px;height:50px;border-radius:12px;border:1px solid var(--bd);background:transparent;display:flex;align-items:center;justify-content:center;flex-shrink:0;overflow:hidden;padding:0;transition:border-color .3s,transform .3s;}.icl:hover{border-color:var(--g);transform:translateY(-4px);}.icl img{width:100%;height:100%;object-fit:contain;display:block;}.icl span{display:none;}
.ics{width:140px;height:50px;border-radius:10px;border:1px solid var(--bd);background:transparent;display:flex;align-items:center;justify-content:center;flex-shrink:0;overflow:hidden;padding:0;transition:border-color .3s;}.ics:hover{border-color:var(--g);}.ics img{width:100%;height:100%;object-fit:contain;display:block;}.ics span{display:none;}
.tlw{position:relative;display:flex;flex-direction:column;max-width:780px;margin:0 auto 52px;}.tlw::before{content:'';position:absolute;left:27px;top:28px;bottom:28px;width:2px;background:linear-gradient(to bottom,#1a6b1a 0%,#E6A817 33%,#22c55e 66%,#2563EB 100%);border-radius:2px;}
.tli{display:flex;gap:28px;align-items:flex-start;padding:20px 0;}.tlic{width:56px;height:56px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:1.2rem;flex-shrink:0;position:relative;z-index:1;}
.cc1{background:#1a6b1a;}.cc2{background:#E6A817;}.cc3{background:#22c55e;}.cc4{background:#2563EB;}
.tlb{flex:1;padding-top:10px;}.tlt{font-family:'Libre Baskerville',serif;font-size:1.1rem;font-weight:700;color:var(--g);margin-bottom:7px;}.tld{font-family:'Inter',sans-serif;font-size:.93rem;color:var(--cr);line-height:1.7;opacity:.85;}
.s3bot{text-align:center;max-width:680px;margin:0 auto;padding-top:44px;border-top:1px solid var(--bd);}
.dblk+.dblk{margin-top:80px;padding-top:80px;border-top:1px solid var(--bd);}
.why-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:24px;margin-top:16px;}.why-card{padding:36px 28px;border-radius:18px;border:1px solid var(--bd);background:var(--bds);position:relative;overflow:hidden;transition:border-color .35s,transform .35s;text-align:center;}.why-card::before{content:'';position:absolute;inset:0;background:radial-gradient(ellipse at top,rgba(201,168,76,.09) 0%,transparent 65%);pointer-events:none;}.why-card:hover{border-color:var(--g);transform:translateY(-6px);}
.why-icon{font-size:2.4rem;margin-bottom:16px;}.why-title{font-family:'Libre Baskerville',serif;font-size:1.05rem;font-weight:700;color:var(--g);margin-bottom:10px;}.why-desc{font-family:'Inter',sans-serif;font-size:.88rem;color:var(--cr);line-height:1.65;opacity:.84;}
.q-block{border-left:3px solid var(--g);padding-left:22px;margin-bottom:32px;}.q-text{font-family:'Libre Baskerville',serif;font-style:italic;font-size:clamp(.95rem,1.25vw,1.1rem);color:var(--cr);line-height:1.72;margin-bottom:12px;}.q-link{font-family:'Inter',sans-serif;font-size:.8rem;color:var(--g);font-weight:600;letter-spacing:.04em;text-decoration:underline;cursor:pointer;margin-bottom:28px;display:inline-block;}
.stats-row{display:flex;gap:18px;flex-wrap:wrap;}.stat-card{flex:1;min-width:130px;padding:22px 18px;border-radius:14px;border:1px solid var(--bd);background:var(--bds);text-align:center;position:relative;overflow:hidden;transition:border-color .3s,transform .3s;}.stat-card::before{content:'';position:absolute;inset:0;background:radial-gradient(ellipse at top left,rgba(201,168,76,.08) 0%,transparent 65%);pointer-events:none;}.stat-card:hover{border-color:var(--g);transform:translateY(-4px);}
.stat-num{font-family:'Libre Baskerville',serif;font-size:clamp(1.5rem,2.2vw,2rem);font-weight:700;color:var(--g);margin-bottom:8px;}.stat-lbl{font-family:'Inter',sans-serif;font-size:.76rem;color:var(--cr);opacity:.8;line-height:1.45;}
.dbl{display:flex;flex-direction:column;gap:16px;overflow:hidden;}
.glass-cta-wrap{position:relative;margin-top:72px;}.glass-cta{padding:56px 48px;border-radius:20px;text-align:center;background:rgba(255,255,255,.03);border:1px solid rgba(201,168,76,.25);backdrop-filter:blur(10px);-webkit-backdrop-filter:blur(10px);box-shadow:0 8px 48px rgba(0,0,0,.4),inset 0 1px 0 rgba(255,255,255,.07);position:relative;overflow:hidden;}.glass-cta::before{content:'';position:absolute;inset:0;background:radial-gradient(ellipse at top center,rgba(201,168,76,.1) 0%,transparent 60%);pointer-events:none;}.glass-cta::after{content:'';position:absolute;top:-60px;left:50%;transform:translateX(-50%);width:240px;height:240px;border-radius:50%;background:radial-gradient(circle,rgba(201,168,76,.12) 0%,transparent 70%);pointer-events:none;}.gc-inner{position:relative;z-index:1;}
.cpills{display:flex;flex-wrap:wrap;justify-content:center;gap:14px;margin-bottom:36px;}.cpill{display:flex;align-items:center;gap:9px;padding:11px 22px;border:1px solid rgba(201,168,76,.25);border-radius:50px;background:rgba(255,255,255,.04);backdrop-filter:blur(8px);font-family:'Inter',sans-serif;font-size:.88rem;color:var(--cr);transition:all .3s;white-space:nowrap;}.cpill:hover{border-color:var(--g);background:rgba(201,168,76,.1);transform:translateY(-3px);}.cpill .pc{color:var(--g);}
.ls-sub{font-family:'Libre Baskerville',serif;font-style:italic;font-size:clamp(.9rem,1.2vw,1.05rem);color:var(--cr);margin-bottom:8px;}.ls-tag{font-family:'Inter',sans-serif;font-size:.78rem;color:var(--g);opacity:.8;letter-spacing:.04em;margin-bottom:28px;}
@media(min-width:961px){.ed.hero{padding-top:160px;padding-bottom:0;}.ed:not(.hero){padding-top:48px;padding-bottom:48px;}}
@media(max-width:960px){.ed{padding:72px 5vw;}.ed.hero{padding-top:100px;}.tc{flex-direction:column;gap:36px;}.tc.fl{flex-direction:column-reverse;}.coli{width:100%;}.ibox{max-width:100%;}.tlw{max-width:100%;}.tlw::before{left:23px;}.tlic{width:48px;height:48px;}.slo::before,.slo::after{width:80px;}.why-grid{grid-template-columns:1fr 1fr;gap:18px;}.stats-row{gap:12px;}.glass-cta{padding:44px 28px;}.dblk+.dblk{margin-top:56px;padding-top:56px;}.hg{font-size:clamp(1.5rem,3.5vw,2.2rem);}.hg-lg{font-size:clamp(1.7rem,4vw,2.4rem);}}
@media(max-width:600px){.ed{padding:56px 5vw 64px;}.ed.hero{padding-top:100px !important;}.tc,.tc.fl{flex-direction:column !important;gap:28px;}.coli{width:100%;}.ibox{max-width:100%;aspect-ratio:3/2;}.br{flex-direction:column;}.bg-btn{width:100%;text-align:center;padding:14px 20px;}.slo::before,.slo::after{width:44px;}.tlw::before{left:18px;top:24px;bottom:24px;}.tlic{width:38px;height:38px;font-size:.88rem;}.tli{gap:14px;padding:15px 0;}.tlb{padding-top:4px;}.tlt{font-size:1rem;}.tld{font-size:.87rem;}.why-grid{grid-template-columns:1fr;gap:14px;}.why-card{padding:26px 20px;}.stats-row{flex-direction:column;gap:10px;}.stat-card{padding:18px 14px;}.cpills{gap:10px;}.cpill{padding:10px 14px;font-size:.8rem;}.glass-cta{padding:32px 18px;}.hg{font-size:clamp(1.3rem,6vw,1.75rem);}.hg-lg{font-size:clamp(1.5rem,6.5vw,2rem);}.hg-sm{font-size:clamp(1.1rem,5vw,1.45rem);}.hg-c{font-size:clamp(1.2rem,5.5vw,1.6rem);}.sub{font-size:.9rem;}.bi{font-size:.88rem;}.gb{margin-bottom:16px;}.dblk+.dblk{margin-top:44px;padding-top:44px;}.q-block{padding-left:14px;}.q-text{font-size:.92rem;}}
`;

const TRUST_ICONS=[{src:"https://pub-8d8c06eb82144fca803dab6ccecd7b41.r2.dev/Images/ws7-1.webp"},{src:"https://pub-8d8c06eb82144fca803dab6ccecd7b41.r2.dev/Images/ws7-2.webp"},{src:"https://pub-8d8c06eb82144fca803dab6ccecd7b41.r2.dev/Images/ws7-3.webp"},{src:"https://pub-8d8c06eb82144fca803dab6ccecd7b41.r2.dev/Images/ws7-4.webp"},{src:"https://pub-8d8c06eb82144fca803dab6ccecd7b41.r2.dev/Images/ws7-5.webp"}];
const TL=[{c:"cc1",i:"🖱️",t:"Acquire",d:"Integrate Google & FB Leads form to enroll students. Answer FAQs using auto-reply flows on WhatsApp."},{c:"cc2",i:"💼",t:"Convert",d:"Setup bulk campaigns to invite students for free classes & webinars. Send class / webinar reminders & regular updates on WhatsApp."},{c:"cc3",i:"😊",t:"Delight",d:"Gather ratings / feedback from students using automated messages. Send post class notifications, study material, recorded video in bulk."},{c:"cc4",i:"🔔",t:"Engage",d:"Setup auto payment reminders for course / examination fees. Accept payment on WhatsApp using frictionless payment integration."}];
const WHY=[{icon:"🎓",title:"Higher Enrollment Rates",desc:"Reach students where they are. WhatsApp's 98% open rate means your enrollment campaigns actually get seen and acted upon."},{icon:"⚡",title:"Quick Onboarding & Admissions",desc:"Automate the admission journey end-to-end from inquiry to enrollment with smart WhatsApp workflows that save time for both staff and students."},{icon:"💬",title:"Real-time Support",desc:"Resolve student doubts instantly with multi-agent chat, automated FAQs and interactive reply buttons available 24×7."}];
const INT_R1=[{src:"https://pub-8d8c06eb82144fca803dab6ccecd7b41.r2.dev/Images/1-1.png",label:"Salesforce"},{src:"https://pub-8d8c06eb82144fca803dab6ccecd7b41.r2.dev/Images/1-2.webp",label:"HubSpot"},{src:"https://pub-8d8c06eb82144fca803dab6ccecd7b41.r2.dev/Images/1-3.png",label:"Shopify"},{src:"https://pub-8d8c06eb82144fca803dab6ccecd7b41.r2.dev/Images/1-4.png",label:"Zoho CRM"},{src:"https://pub-8d8c06eb82144fca803dab6ccecd7b41.r2.dev/Images/1-5.png",label:"Zapier"},{src:"https://pub-8d8c06eb82144fca803dab6ccecd7b41.r2.dev/Images/1-6.png",label:"Slack"},{src:"https://pub-8d8c06eb82144fca803dab6ccecd7b41.r2.dev/Images/1-7.png",label:"WooCommerce"},{src:"https://pub-8d8c06eb82144fca803dab6ccecd7b41.r2.dev/Images/1-8.png",label:"Google Sheets"}];
const INT_R2=[{src:"https://pub-8d8c06eb82144fca803dab6ccecd7b41.r2.dev/Images/1-9.png",label:"Razorpay"},{src:"https://pub-8d8c06eb82144fca803dab6ccecd7b41.r2.dev/Images/1-10.webp",label:"Stripe"},{src:"https://pub-8d8c06eb82144fca803dab6ccecd7b41.r2.dev/Images/1-11.png",label:"Intercom"},{src:"https://pub-8d8c06eb82144fca803dab6ccecd7b41.r2.dev/Images/1-12.png",label:"Freshdesk"},{src:"https://pub-8d8c06eb82144fca803dab6ccecd7b41.r2.dev/Images/1-13.png",label:"Mailchimp"},{src:"https://pub-8d8c06eb82144fca803dab6ccecd7b41.r2.dev/Images/1-14.png",label:"Pipedrive"},{src:"https://pub-8d8c06eb82144fca803dab6ccecd7b41.r2.dev/Images/1-15.png",label:"Zendesk"},{src:"https://pub-8d8c06eb82144fca803dab6ccecd7b41.r2.dev/Images/1-16.png",label:"Google Analytics"}];

function Img({src,alt}:{src:string;alt:string}){return(<div className="ibox"><img src={src} alt={alt} loading="lazy" decoding="async" /></div>);}
function Bullets({items}:{items:string[]}){return(<ul className="bl">{items.map((t,i)=>(<li className="bi" key={i}><span className="tk">✅</span><span>{t}</span></li>))}</ul>);}
function Track({items,small=false,reverse=false}:{items:{src:string;label?:string}[];small?:boolean;reverse?:boolean}){const d=[...items,...items];return(<div className={"s-track"+(reverse?" rv":"")}>{d.map((item,i)=>small?<div className="ics" key={i}><img src={item.src} alt={item.label||""} loading="lazy" decoding="async" /></div>:<div className="icl" key={i}><img src={item.src} alt={item.label||""} loading="lazy" decoding="async" /></div>)}</div>);}

export default function EdTechPage(){
  const[modalOpen,setModalOpen]=useState(false);
  const CTA=()=><div className="br"><button className="bg-btn" onClick={()=>setModalOpen(true)}>Contact Us</button></div>;

  return(<>
    <style>{CSS}</style>
    <GoogleForm isOpen={modalOpen} onClose={()=>setModalOpen(false)}/>

    <section className="ed b1 hero" style={{paddingTop:160,paddingBottom:0}}><div className="inn"><div className="tc fl"><div className="coli"><Img src="https://pub-8d8c06eb82144fca803dab6ccecd7b41.r2.dev/Images/ws7img1.webp" alt="EdTech WhatsApp hero"/></div><div className="col"><div className="gb"/><h1 className="hg hg-lg">Now enroll new students and keep them updated on WhatsApp</h1><Bullets items={["Send personalized reminders for upcoming tests, fee payments, results, etc.","Make education more accessible, affordable and flexible for students.","Personalized chat-based conversations on WhatsApp."]}/><CTA/></div></div></div></section>

    <section className="ed b2" style={{padding:"80px 0 88px"}}><div style={{padding:"0 7vw",marginBottom:44}}><div className="inn" style={{textAlign:"center"}}><h2 className="hg hg-c" style={{marginBottom:0,fontSize:"clamp(1.2rem,1.8vw,1.7rem)"}}>Edutech brands ❤️</h2></div></div><div className="slo fb2"><Track items={TRUST_ICONS}/></div></section>

    <section className="ed b3"><div className="inn"><div style={{textAlign:"center",marginBottom:52}}><div className="gb gb-c"/><h2 className="hg hg-c" style={{marginBottom:0}}>Help students &amp; aspirants avail courses &amp; curriculum-related information instantly on WhatsApp</h2></div><div className="tlw">{TL.map((item,i)=>(<div className="tli" key={i}><div className={"tlic "+item.c}>{item.i}</div><div className="tlb"><div className="tlt">{item.t}</div><p className="tld">{item.d}</p></div></div>))}</div><div className="s3bot"><div className="gb gb-c"/><h3 className="hg hg-sm hg-c" style={{marginBottom:0}}>Deploy powerful WhatsApp features for every step of your Edutech business</h3></div></div></section>

    <section className="ed b1"><div className="inn">
      <div className="dblk"><div className="tc"><div className="col"><div className="gb"/><h2 className="hg hg-sm">Capture Student Interest with Engaging Ad Campaigns</h2><Bullets items={["Leverage Click To WhatsApp Ads for inviting prospective students for a conversation","Use a well-placed WhatsApp widget to engage students/parents and nudge them towards a course purchase","Become accessible with easy-to-scan WhatsApp QR Codes","Use WhatsApp Links to reach students on Social Media"]}/><CTA/></div><div className="coli"><Img src="https://pub-8d8c06eb82144fca803dab6ccecd7b41.r2.dev/Images/ws7img2.webp" alt="Capture student interest"/></div></div></div>
      <div className="dblk"><div className="tc fl"><div className="coli"><Img src="https://pub-8d8c06eb82144fca803dab6ccecd7b41.r2.dev/Images/ws7img3.webp" alt="Nudge towards admission"/></div><div className="col"><div className="gb"/><h2 className="hg hg-sm">Nudge them towards admission with interactive conversations</h2><Bullets items={["Use a Green Tick Verified account to build trust with students","Share course updates on WhatsApp to keep students engaged","Collect payments on WhatsApp with RazorPay & PayU integrations","Leverage automated workflows on WhatsApp to streamline self-admission process"]}/><CTA/></div></div></div>
    </div></section>

    <section className="ed b2"><div className="inn">
      <div className="dblk"><div className="tc"><div className="col"><div className="gb"/><h2 className="hg hg-sm">Keep students engaged throughout their course with WhatsApp automations</h2><Bullets items={["Keep students up-to-date on curriculum with regular Timetable Updates","Share news & announcements with personalized automated notifications on WhatsApp","Invite students for extra-curriculars via WhatsApp for more conversion","Send personalized & timely study materials to students on WhatsApp"]}/><CTA/></div><div className="coli"><Img src="https://pub-8d8c06eb82144fca803dab6ccecd7b41.r2.dev/Images/ws7img4.webp" alt="Keep students engaged"/></div></div></div>
      <div className="dblk"><div className="tc fl"><div className="coli"><Img src="https://pub-8d8c06eb82144fca803dab6ccecd7b41.r2.dev/Images/ws7img5.webp" alt="Resolve student queries"/></div><div className="col"><div className="gb"/><h2 className="hg hg-sm">Leverage WhatsApp to quickly resolve student queries with interactive messages and automations</h2><Bullets items={["Solve student queries at scale by setting up custom auto-replies for student FAQs","Streamline your support with Multi-agent chat on WhatsApp","Offer a seamless support experience with Quick Replies & List messages","Collect timely feedback with WhatsApp automation"]}/><CTA/></div></div></div>
    </div></section>

    <section className="ed b3"><div className="inn"><div style={{textAlign:"center",marginBottom:48}}><div className="gb gb-c"/><h2 className="hg hg-c" style={{marginBottom:12}}>Why WhatsApp for EdTech</h2><p className="sub" style={{maxWidth:560,margin:"0 auto"}}>Learn from the best in business</p></div><div className="why-grid">{WHY.map((w,i)=>(<div className="why-card" key={i}><div className="why-icon">{w.icon}</div><div className="why-title">{w.title}</div><p className="why-desc">{w.desc}</p></div>))}</div></div></section>

    <section className="ed b1"><div className="inn"><div className="tc"><div className="col"><div className="gb"/><div className="q-block"><p className="q-text">"95% of our customer communications across the funnel are handled on WhatsApp , improving our message delivery and read rates further leaving me less concerned about missing new business opportunities."</p></div><span className="q-link">Read Now →</span><div className="stats-row"><div className="stat-card"><div className="stat-num">95%</div><div className="stat-lbl">Communications handled by WhatsApp</div></div><div className="stat-card"><div className="stat-num">4hrs</div><div className="stat-lbl">Support time saved daily through WhatsApp Automation</div></div><div className="stat-card"><div className="stat-num">+30%</div><div className="stat-lbl">Higher open rate vs. email</div></div></div></div><div className="coli"><Img src="https://pub-8d8c06eb82144fca803dab6ccecd7b41.r2.dev/Images/ws7img6.webp" alt="EdTech success story"/></div></div></div></section>

    <section className="ed b2"><div className="inn" style={{textAlign:"center",marginBottom:52}}><div className="gb gb-c"/><h2 className="hg hg-c" style={{marginBottom:0}}>Seamless integration with 15+ popular business platforms</h2></div><div className="dbl"><div className="slo fb2"><Track items={INT_R1} small/></div><div className="slo fb2"><Track items={INT_R2} small reverse/></div></div></section>

    <section className="ed b3"><div className="inn">
      <div className="tc"><div className="col"><div className="gb"/><h2 className="hg">Grow your Edtech Business on WhatsApp</h2><p className="ls-sub">Start your 14 day free trial today</p><p className="ls-tag">No Credit Card Required*</p><CTA/></div><div className="coli"><Img src="https://pub-8d8c06eb82144fca803dab6ccecd7b41.r2.dev/Images/ws7img7.webp" alt="Grow your EdTech business"/></div></div>
      <div className="glass-cta-wrap"><div className="glass-cta"><div className="gc-inner"><div className="gb gb-c"/><h2 className="hg hg-c" style={{marginBottom:32}}>Get Started</h2><div className="cpills">{["Engage & Re-engage Prospects","Drive Sales","Deliver higher CSAT","Support at Scale"].map((label,i)=>(<div className="cpill" key={i}><span className="pc">✅</span><span>{label}</span></div>))}</div><div className="br" style={{justifyContent:"center"}}><button className="bg-btn" style={{fontSize:"1rem",padding:"15px 40px"}} onClick={()=>setModalOpen(true)}>Contact Us</button></div></div></div></div>
    </div></section>
  </>);
}
