import { useState } from "react";
import GoogleForm from "../ui/GoogleForm";
import ContactUsForm from "@/pages/ContactUsForm";

const CSS = `
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0;}
body{background:#0A0A0A;color:#fff;font-family:'Inter',sans-serif;overflow-x:hidden;}
:root{--g:#C9A84C;--g2:#E0B85A;--cr:#F5F0E8;--b1:#0A0A0A;--b2:#0E0E0E;--b3:#111111;--bd:rgba(201,168,76,.18);--bds:rgba(201,168,76,.07);}
.hw{width:100%;padding:24px 7vw 16px;position:relative;}.hw.b1{background:var(--b1);}.hw.b2{background:var(--b2);}.hw.b3{background:var(--b3);}.hw+.hw{border-top:1px solid var(--bd);}
.hw.hero{padding-top:160px;padding-bottom:0 !important;}
@media(min-width:961px){.hw.hero{padding-top:160px !important;padding-bottom:0 !important;}.hw:not(.hero){padding-top:48px;padding-bottom:48px;}}
.inn{max-width:1200px;margin:0 auto;}
.tc{display:flex;align-items:center;gap:64px;}.tc .col{flex:1;min-width:0;}.tc .coli{flex:1;display:flex;justify-content:center;align-items:center;}
.hw.hero .tc{align-items:flex-start;}
.ibox{width:100%;max-width:510px;aspect-ratio:4/3;border-radius:0;border:none;background:transparent;overflow:hidden;}.ibox img{width:100%;height:100%;object-fit:contain;border-radius:0;display:block;}
.hg{font-family:'Libre Baskerville',serif;font-size:clamp(1.7rem,2.5vw,2.5rem);font-weight:700;color:var(--g);line-height:1.27;letter-spacing:-.01em;margin-bottom:24px;}
.hg-sm{font-size:clamp(1.25rem,1.8vw,1.85rem);}.hg-lg{font-size:clamp(1.9rem,3vw,2.9rem);}.hg-c{text-align:center;}
.sub{font-family:'Inter',sans-serif;font-size:clamp(.88rem,1.05vw,1rem);color:var(--cr);line-height:1.73;opacity:.88;}
.gb{width:48px;height:3px;background:var(--g);border-radius:2px;margin-bottom:20px;}.gb-c{margin:0 auto 20px;}
.bl{list-style:none;display:flex;flex-direction:column;gap:12px;margin-bottom:28px;}.bi{display:flex;align-items:flex-start;gap:11px;font-family:'Inter',sans-serif;font-size:clamp(.86rem,1vw,.98rem);color:var(--cr);line-height:1.68;}.bi .tk{flex-shrink:0;margin-top:2px;}
.br{display:flex;flex-wrap:wrap;gap:14px;}.bg-btn{background:var(--g);color:#0A0A0A;font-family:'Inter',sans-serif;font-weight:700;font-size:.9rem;padding:13px 30px;border:none;border-radius:6px;cursor:pointer;letter-spacing:.03em;transition:all .25s;white-space:nowrap;}.bg-btn:hover{background:var(--g2);transform:translateY(-2px);box-shadow:0 8px 24px rgba(201,168,76,.32);}
.slo{position:relative;overflow:hidden;padding:10px 0;}.slo::before,.slo::after{content:'';position:absolute;top:0;bottom:0;width:160px;z-index:2;pointer-events:none;}
.slo.fb1::before{left:0;background:linear-gradient(to right,#0A0A0A 25%,transparent);}.slo.fb1::after{right:0;background:linear-gradient(to left,#0A0A0A 25%,transparent);}
.slo.fb2::before{left:0;background:linear-gradient(to right,#0E0E0E 25%,transparent);}.slo.fb2::after{right:0;background:linear-gradient(to left,#0E0E0E 25%,transparent);}
.slo.fb3::before{left:0;background:linear-gradient(to right,#111111 25%,transparent);}.slo.fb3::after{right:0;background:linear-gradient(to left,#111111 25%,transparent);}
.s-track{display:flex;gap:22px;width:max-content;animation:mq 22s linear infinite;}.s-track.rv{animation-direction:reverse;animation-duration:18s;}.s-track:hover{animation-play-state:paused;}
@keyframes mq{from{transform:translateX(0);}to{transform:translateX(-50%);}}
.icl,.ics{width:140px;height:50px;border-radius:8px;border:1px solid var(--bd);background:var(--bds);display:flex;align-items:center;justify-content:center;flex-shrink:0;overflow:hidden;padding:0;transition:border-color .3s,transform .3s;}.icl:hover,.ics:hover{border-color:var(--g);transform:translateY(-3px);}.icl img,.ics img{width:100%;height:100%;object-fit:contain;display:block;}.icl span,.ics span{display:none;}
.tlw{position:relative;display:flex;flex-direction:column;max-width:780px;margin:0 auto 48px;}.tlw::before{content:'';position:absolute;left:27px;top:28px;bottom:28px;width:2px;background:linear-gradient(to bottom,#1a6b1a 0%,#E6A817 35%,#22c55e 65%,#2563EB 100%);border-radius:2px;}
.tli{display:flex;gap:28px;align-items:flex-start;padding:20px 0;}.tlic{width:56px;height:56px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:1.2rem;flex-shrink:0;position:relative;z-index:1;}
.cc1{background:#1a6b1a;}.cc2{background:#E6A817;}.cc3{background:#22c55e;}.cc4{background:#2563EB;}
.tlb{flex:1;padding-top:10px;}.tlt{font-family:'Libre Baskerville',serif;font-size:1.1rem;font-weight:700;color:var(--g);margin-bottom:7px;}.tld{font-family:'Inter',sans-serif;font-size:.93rem;color:var(--cr);line-height:1.7;opacity:.85;}
.s3bot{text-align:center;max-width:760px;margin:0 auto;padding-top:36px;border-top:1px solid var(--bd);}.s3bot strong{color:var(--g);font-weight:600;}
.dblk+.dblk{margin-top:52px;padding-top:52px;border-top:1px solid var(--bd);}
.dbl{display:flex;flex-direction:column;gap:16px;overflow:hidden;}
.torn-wrap{position:relative;margin-top:52px;}.torn-card{background:rgba(201,168,76,.07);border:1px solid var(--bd);border-radius:4px;padding:48px 48px;position:relative;overflow:hidden;}
.torn-card::before{content:'';position:absolute;top:-1px;left:0;right:0;height:20px;background:var(--b1);clip-path:polygon(0% 0%,1.5% 100%,3% 15%,4.5% 90%,6% 5%,7.5% 95%,9% 10%,10.5% 88%,12% 3%,13.5% 92%,15% 18%,16.5% 85%,18% 8%,19.5% 94%,21% 12%,22.5% 80%,24% 5%,25.5% 96%,27% 20%,28.5% 82%,30% 6%,31.5% 91%,33% 16%,34.5% 86%,36% 3%,37.5% 94%,39% 22%,40.5% 78%,42% 8%,43.5% 93%,45% 14%,46.5% 88%,48% 4%,49.5% 97%,51% 18%,52.5% 83%,54% 5%,55.5% 91%,57% 20%,58.5% 80%,60% 6%,61.5% 95%,63% 12%,64.5% 86%,66% 3%,67.5% 93%,69% 22%,70.5% 78%,72% 8%,73.5% 96%,75% 15%,76.5% 84%,78% 4%,79.5% 92%,81% 18%,82.5% 82%,84% 6%,85.5% 94%,87% 14%,88.5% 88%,90% 3%,91.5% 95%,93% 20%,94.5% 80%,96% 8%,97.5% 92%,100% 0%);}
.torn-card::after{content:'';position:absolute;bottom:-1px;left:0;right:0;height:20px;background:var(--b1);clip-path:polygon(0% 100%,1.5% 0%,3% 85%,4.5% 10%,6% 95%,7.5% 5%,9% 90%,10.5% 12%,12% 97%,13.5% 8%,15% 82%,16.5% 15%,18% 92%,19.5% 6%,21% 88%,22.5% 20%,24% 95%,25.5% 4%,27% 80%,28.5% 18%,30% 94%,31.5% 9%,33% 84%,34.5% 14%,36% 97%,37.5% 6%,39% 78%,40.5% 22%,42% 92%,43.5% 7%,45% 86%,46.5% 12%,48% 96%,49.5% 3%,51% 82%,52.5% 17%,54% 95%,55.5% 9%,57% 80%,58.5% 20%,60% 94%,61.5% 5%,63% 88%,64.5% 14%,66% 97%,67.5% 7%,69% 78%,70.5% 22%,72% 92%,73.5% 4%,75% 85%,76.5% 16%,78% 96%,79.5% 8%,81% 82%,82.5% 18%,84% 94%,85.5% 6%,87% 86%,88.5% 12%,90% 97%,91.5% 5%,93% 80%,94.5% 20%,96% 92%,97.5% 8%,100% 100%);}
.torn-inner{text-align:center;}
.tpills{display:flex;flex-wrap:wrap;justify-content:center;gap:14px;margin-bottom:36px;}.tpill{display:flex;align-items:center;gap:9px;padding:11px 22px;border:1px solid var(--bd);border-radius:50px;background:rgba(201,168,76,.05);font-family:'Inter',sans-serif;font-size:.88rem;color:var(--cr);transition:all .3s;white-space:nowrap;}.tpill:hover{border-color:var(--g);background:rgba(201,168,76,.1);transform:translateY(-3px);}.tpill .pc{color:var(--g);}
.ls-sub{font-family:'Libre Baskerville',serif;font-style:italic;font-size:clamp(.9rem,1.2vw,1.05rem);color:var(--cr);margin-bottom:8px;}.ls-tag{font-family:'Inter',sans-serif;font-size:.78rem;color:var(--g);opacity:.8;letter-spacing:.04em;margin-bottom:28px;}
@media(max-width:960px){.hw{padding:20px 5vw 12px;}.hw.hero{padding-top:108px !important;padding-bottom:0 !important;}.tc{flex-direction:column;gap:36px;}.tc.fl{flex-direction:column-reverse;}.hw.hero .tc{align-items:flex-start;}.coli{width:100%;}.ibox{max-width:100%;}.tlw{max-width:100%;}.tlw::before{left:23px;}.tlic{width:48px;height:48px;}.slo::before,.slo::after{width:80px;}.torn-card{padding:44px 28px;}.dblk+.dblk{margin-top:44px;padding-top:44px;}.hg{font-size:clamp(1.5rem,3.5vw,2.2rem);}.hg-lg{font-size:clamp(1.7rem,4vw,2.4rem);}}
@media(max-width:600px){.hw{padding:28px 5vw 24px;}.hw.hero{padding-top:100px !important;padding-bottom:0 !important;}.tc,.tc.fl{flex-direction:column !important;gap:28px;}.hw.hero .tc{align-items:flex-start !important;}.coli{width:100%;}.ibox{max-width:100%;aspect-ratio:3/2;}.br{flex-direction:column;}.bg-btn{width:100%;text-align:center;padding:14px 20px;}.slo::before,.slo::after{width:44px;}.tlw::before{left:18px;top:24px;bottom:24px;}.tlic{width:38px;height:38px;font-size:.88rem;}.tli{gap:14px;padding:15px 0;}.tlb{padding-top:4px;}.tlt{font-size:1rem;}.tld{font-size:.87rem;}.tpills{gap:10px;}.tpill{padding:10px 14px;font-size:.8rem;}.torn-card{padding:32px 18px;}.torn-card::before,.torn-card::after{height:14px;}.hg{font-size:clamp(1.3rem,6vw,1.75rem);}.hg-lg{font-size:clamp(1.5rem,6.5vw,2rem);}.hg-sm{font-size:clamp(1.1rem,5vw,1.45rem);}.hg-c{font-size:clamp(1.2rem,5.5vw,1.6rem);}.sub{font-size:.9rem;}.bi{font-size:.88rem;}.gb{margin-bottom:16px;}.dblk+.dblk{margin-top:44px;padding-top:44px;}}
`;


const TL=[{c:"cc1",i:"🖱️",t:"Acquire",d:"Integrate your online store for capturing qualified leads & drive conversions. Answer FAQs quickly via custom auto-replies and help patients in making the right decisions."},{c:"cc2",i:"💼",t:"Convert",d:"Upsell & Cross-sell with personalized health checkup, supplement, etc., recommendations based on past purchases. Send payment links for collecting payment on WhatsApp & quick settlements."},{c:"cc3",i:"😊",t:"Delight",d:"Support clients at scale 24×7 on WhatsApp and Gather ratings / feedback from clients using WhatsApp automated flows."},{c:"cc4",i:"🔔",t:"Engage",d:"Promote customer testimonials, success stories and user generated content as social proof. Send regular tips & tricks on how to lead a healthy lifestyle."}];
const INT_R1=[{src:"https://pub-8d8c06eb82144fca803dab6ccecd7b41.r2.dev/Images/1-1.png",label:"Salesforce"},{src:"https://pub-8d8c06eb82144fca803dab6ccecd7b41.r2.dev/Images/1-2.webp",label:"HubSpot"},{src:"https://pub-8d8c06eb82144fca803dab6ccecd7b41.r2.dev/Images/1-3.png",label:"Shopify"},{src:"https://pub-8d8c06eb82144fca803dab6ccecd7b41.r2.dev/Images/1-4.png",label:"Zoho CRM"},{src:"https://pub-8d8c06eb82144fca803dab6ccecd7b41.r2.dev/Images/1-5.png",label:"Zapier"},{src:"https://pub-8d8c06eb82144fca803dab6ccecd7b41.r2.dev/Images/1-6.png",label:"Slack"},{src:"https://pub-8d8c06eb82144fca803dab6ccecd7b41.r2.dev/Images/1-7.png",label:"WooCommerce"},{src:"https://pub-8d8c06eb82144fca803dab6ccecd7b41.r2.dev/Images/1-8.png",label:"Google Sheets"}];
const INT_R2=[{src:"https://pub-8d8c06eb82144fca803dab6ccecd7b41.r2.dev/Images/1-9.png",label:"Razorpay"},{src:"https://pub-8d8c06eb82144fca803dab6ccecd7b41.r2.dev/Images/1-10.webp",label:"Stripe"},{src:"https://pub-8d8c06eb82144fca803dab6ccecd7b41.r2.dev/Images/1-11.png",label:"Intercom"},{src:"https://pub-8d8c06eb82144fca803dab6ccecd7b41.r2.dev/Images/1-12.png",label:"Freshdesk"},{src:"https://pub-8d8c06eb82144fca803dab6ccecd7b41.r2.dev/Images/1-13.png",label:"Mailchimp"},{src:"https://pub-8d8c06eb82144fca803dab6ccecd7b41.r2.dev/Images/1-14.png",label:"Pipedrive"},{src:"https://pub-8d8c06eb82144fca803dab6ccecd7b41.r2.dev/Images/1-15.png",label:"Zendesk"},{src:"https://pub-8d8c06eb82144fca803dab6ccecd7b41.r2.dev/Images/1-16.png",label:"Google Analytics"}];

function Img({src,alt}:{src:string;alt:string}){return(<div className="ibox"><img src={src} alt={alt} loading="lazy" decoding="async" /></div>);}
function Bullets({items}:{items:string[]}){return(<ul className="bl">{items.map((t,i)=>(<li className="bi" key={i}><span className="tk">✅</span><span>{t}</span></li>))}</ul>);}
function Track({items,small=false,reverse=false}:{items:{src:string;label?:string}[];small?:boolean;reverse?:boolean}){const d=[...items,...items];return(<div className={`s-track${reverse?" rv":""}`}>{d.map((item,i)=>small?<div className="ics" key={i}><img src={item.src} alt={item.label||""} loading="lazy" decoding="async" /></div>:<div className="icl" key={i}><img src={item.src} alt={item.label||""} loading="lazy" decoding="async" /></div>)}</div>);}

export default function HealthWellnessPage(){
  const[modalOpen,setModalOpen]=useState(false);
  const CTA=()=><div className="br"></div>;

  return(<>
    <style>{CSS}</style>
    <GoogleForm isOpen={modalOpen} onClose={()=>setModalOpen(false)}/>

    <section className="hw b1 hero"><div className="inn"><div className="tc"><div className="col"><div className="gb"/><h1 className="hg hg-lg">Use WhatsApp to grow your Health &amp; Wellness business</h1><Bullets items={["Recover abandoned carts with automated reminders","Promote deals and discounts using WhatsApp broadcasts","Promote your offerings using WhatsApp catalog"]}/><CTA/></div><div className="coli"><Img src="https://pub-8d8c06eb82144fca803dab6ccecd7b41.r2.dev/Images/PortfolioProjects/WhatsAppInterakt-By-Industry/Health-Wellness/Health-Wellness-section1.webp" alt="Health & Wellness WhatsApp hero"/></div></div></div></section>

   

    <section className="hw b3"><div className="inn"><div style={{textAlign:"center",marginBottom:36}}><div className="gb gb-c"/><h2 className="hg hg-c" style={{marginBottom:0}}>Create delightful experiences on WhatsApp</h2></div><div className="tlw">{TL.map((item,i)=>(<div className="tli" key={i}><div className={`tlic ${item.c}`}>{item.i}</div><div className="tlb"><div className="tlt">{item.t}</div><p className="tld">{item.d}</p></div></div>))}</div><div className="s3bot"><h3 className="hg hg-sm hg-c" style={{marginBottom:14}}>How to use WhatsApp Business API to grow your business</h3><p className="sub">The personal care, health and wellness industry is projected to grow to $39.56 billion and then continue to scale at an annual rate of 5 10%. See how leading brands are using <strong style={{color:"var(--g)",fontWeight:600}}>WhatsApp Business API</strong> to keep customers engaged in this growing competition.</p></div></div></section>

    <section className="hw b1"><div className="inn"><div className="tc"><div className="col"><div className="gb"/><h2 className="hg hg-sm">Capture buyer intent of health and wellness shoppers using WhatsApp</h2><Bullets items={["Run click to WhatsApp ads to capture consumer information","Start conversations on your website with a WhatsApp widget","Use QR codes in print ads and packaging to get opt-ins","Share WhatsApp links on social media and other channels"]}/><CTA/></div><div className="coli"><Img src="https://pub-8d8c06eb82144fca803dab6ccecd7b41.r2.dev/Images/PortfolioProjects/WhatsAppInterakt-By-Industry/Health-Wellness/Health-Wellness-section3.webp" alt="Capture buyer intent"/></div></div></div></section>

    <section className="hw b2"><div className="inn"><div className="tc fl"><div className="coli"><Img src="https://pub-8d8c06eb82144fca803dab6ccecd7b41.r2.dev/Images/PortfolioProjects/WhatsAppInterakt-By-Industry/Health-Wellness/Health-Wellness-section4.webp" alt="Convert opt-ins"/></div><div className="col"><div className="gb"/><h2 className="hg hg-sm">Convert WhatsApp opt-ins into customers using automations and conversational commerce</h2><Bullets items={["Create an automated welcome series to understand buyer needs","Share product details and highlights with media files","Create WhatsApp checkout links and take payments for orders through chat","Set up automated reminders for health and wellness product restocks","Set up a workflow to convert COD orders into prepaid"]}/><CTA/></div></div></div></section>

    <section className="hw b3"><div className="inn"><div className="tc"><div className="col"><div className="gb"/><h2 className="hg hg-sm">Increase repeat sales and improve customer experience with personalized WhatsApp campaigns</h2><Bullets items={["Offer shopping assistance to conscious health and wellness shoppers","Promote customer testimonials, success stories and user generated content as social proof"]}/><CTA/></div><div className="coli"><Img src="https://pub-8d8c06eb82144fca803dab6ccecd7b41.r2.dev/Images/PortfolioProjects/WhatsAppInterakt-By-Industry/Health-Wellness/Health-Wellness-section5.webp" alt="Increase repeat sales"/></div></div></div></section>

    <section className="hw b1"><div className="inn"><div className="tc fl"><div className="coli"><Img src="https://pub-8d8c06eb82144fca803dab6ccecd7b41.r2.dev/Images/PortfolioProjects/WhatsAppInterakt-By-Industry/Health-Wellness/Health-Wellness-section6.webp" alt="Delight customers"/></div><div className="col"><div className="gb"/><h2 className="hg hg-sm">Delight your customers before, during and after a purchase</h2><Bullets items={["Offer proactive customer support and shopping assistance before, during and after purchase","Automate transactional and order status alerts","Reduce NDRs and RTOs with delivery and shipping notifications","Request product reviews, ratings and customer feedback on WhatsApp"]}/><CTA/></div></div></div></section>

  

    <section className="hw b3"><div className="inn"><div className="tc fl"><div className="coli"><Img src="https://pub-8d8c06eb82144fca803dab6ccecd7b41.r2.dev/Images/PortfolioProjects/WhatsAppInterakt-By-Industry/Health-Wellness/Health-Wellness-section7.webp" alt="Why WhatsApp for health and wellness"/></div><div className="col"><div className="gb"/><h2 className="hg hg-sm">Why use WhatsApp for health and wellness business?</h2><Bullets items={["Messages getting read within 3 minutes of being sent on average","98% open rate of WhatsApp broadcast and transactional messages","45 57% average click through rate on messages","53% higher customer engagement rate across the buyer cycle"]}/></div></div></div></section>

    <ContactUsForm/>
  </>);
}
