#!/usr/bin/env python3
"""Separate article bodies from article metadata.

blogs.ts held both, and BlogPost was imported eagerly in App.tsx, so every page
on the site downloaded every article — 6.1 MB of JavaScript to read the contact
page. Metadata stays in a small module the listing can import; each body becomes
a JSON file the post page fetches only when someone opens that post.
"""
import json, pathlib, re

ROOT = pathlib.Path(__file__).resolve().parents[2]
SRC = ROOT / "src" / "data" / "blogs.ts"
OUT = ROOT / "public" / "blog-data"
OUT.mkdir(parents=True, exist_ok=True)

text = SRC.read_text()
# Records are `{ id: "...", ... content: `...` }` — walk them with a scanner so a
# backtick inside prose cannot end a body early.
recs = []
i = 0
while True:
    m = re.compile(r'\n  \{\n    id: "([^"]+)",').search(text, i)
    if not m:
        break
    slug = m.group(1)
    head_end = text.index("content: `", m.end())
    head = text[m.end():head_end]
    j = head_end + len("content: `")
    body = []
    while j < len(text):
        c = text[j]
        if c == "\\":
            body.append(text[j:j+2]); j += 2; continue
        if c == "`":
            break
        body.append(c); j += 1
    content = "".join(body)
    def field(name, default=""):
        mm = re.search(rf'{name}: "((?:[^"\\]|\\.)*)"', head)
        return mm.group(1).replace('\\"', '"') if mm else default
    tags = re.search(r"tags: \[(.*?)\]", head, re.S)
    rt = re.search(r"readTime: (\d+)", head)
    recs.append({
        "id": slug, "title": field("title"), "excerpt": field("excerpt"),
        "category": field("category"),
        "tags": re.findall(r'"((?:[^"\\]|\\.)*)"', tags.group(1)) if tags else [],
        "readTime": int(rt.group(1)) if rt else 10,
        "date": field("date"),
        "content": content.replace("\\`", "`").replace("\\${", "${").replace("\\\\", "\\"),
    })
    i = j

for f in OUT.glob("*.json"):
    f.unlink()
for r in recs:
    (OUT / f"{r['id']}.json").write_text(json.dumps({"content": r["content"]}, ensure_ascii=False))

def esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ")

lines = ["// GENERATED by tools/blog/split_content.py — do not edit by hand.",
         "//",
         "// Metadata only. Article bodies live in public/blog-data/<id>.json and are",
         "// fetched by the post page, so opening any other page on the site no longer",
         "// downloads every article ever written.",
         "export type BlogPost = {",
         "  id: string; title: string; excerpt: string; category: string;",
         "  tags: string[]; readTime: number; date: string;",
         "};",
         "",
         "export const blogs: BlogPost[] = ["]
for r in recs:
    tags = ", ".join(f'"{esc(t)}"' for t in r["tags"])
    lines.append(f'  {{ id: "{esc(r["id"])}", title: "{esc(r["title"])}", '
                 f'excerpt: "{esc(r["excerpt"])}", category: "{esc(r["category"])}", '
                 f'tags: [{tags}], readTime: {r["readTime"]}, date: "{r["date"]}" }},')
lines.append("];")
(ROOT / "src" / "data" / "blogIndex.ts").write_text("\n".join(lines) + "\n")

idx_kb = len("\n".join(lines)) / 1024
body_kb = sum(f.stat().st_size for f in OUT.glob("*.json")) / 1024
print(f"  {len(recs)} posts")
print(f"  src/data/blogIndex.ts   {idx_kb:.0f} KB  (was {SRC.stat().st_size/1024:.0f} KB)")
print(f"  public/blog-data/*.json {body_kb/1024:.1f} MB across {len(recs)} files")
