// FAQPage JSON-LD for blog posts that include a visible "Frequently Asked
// Questions" section. Keyed by blog id; the Q&A text here must match what
// renders on the page — this is a schema mirror, not separate content.
import { createFAQSchema } from './schema';

export const BLOG_FAQ: Record<string, { question: string; answer: string }[]> = {
  'web-development-company-pune-css-baseline-2026-features': [
    { question: "Do these new CSS features work in older browsers, or on older phones with outdated WebViews?", answer: "Not universally, and that's expected rather than a flaw. Baseline status means the current stable release of every major browser engine supports the feature — it does not mean every device already in use has updated to that version. Older Android phones running outdated system WebViews, and any browser that hasn't been updated in a year or more, may not recognize some or all of these features yet. That's exactly why a competent build wraps each of them in a fallback (a plain color, a fixed-height field, a JavaScript-toggled class) so unsupported devices still get a working experience, just without the extra polish — nothing breaks, it simply looks and behaves the way it did before these features existed." },
    { question: "Does field-sizing: content fully replace the JavaScript autosize libraries developers use today?", answer: "For the common case, yes — but not universally yet, so it's not a blanket replacement on every project as of today. Where field-sizing: content is supported (Chrome 123+, Firefox 152+, Safari 26.2+, Edge 123+), it removes the need for scroll-height listeners and manual resize logic entirely, and it's typically smoother because it's handled by the browser's own layout engine rather than reacting after the fact in JavaScript. The sensible approach right now is to use it as the primary method with a @supports fallback to the existing JavaScript autosize behaviour for browsers that don't yet recognize the CSS property, rather than deleting the library outright — which is a decision your developer should make explicitly, not by default." },
    { question: "Is contrast-color() the same thing as choosing brand colors — does it replace a designer's color decisions?", answer: "No — it's a safety mechanism for text legibility, not a color-choosing tool for a brand palette. A designer still chooses the brand colors, the accent tones, the overall visual identity — contrast-color() only decides, at the moment a background color is applied, whether black or white (or a supplied alternative) text will read more clearly against it. It's most valuable specifically where the background color is dynamic or unpredictable at design time: a CMS-driven category color, a per-campaign accent on a donation platform, or a user-set theme color — situations where nobody can manually verify every possible combination in advance. For a fixed, designer-chosen palette, manual contrast checking during design remains entirely appropriate." },
    { question: "Will using @starting-style entry animations cause problems for users who have \"reduced motion\" turned on?", answer: "Only if the developer forgets to account for it, which is a general animation best practice rather than something specific to this feature. Any transition or animation — whether built with @starting-style, plain CSS transitions, or a JavaScript library — should be wrapped in a prefers-reduced-motion media query check, so users who've enabled that operating system accessibility setting see the content appear instantly rather than sliding, fading, or scaling in. @starting-style doesn't change this obligation one way or the other; it just makes the animation itself easier to write correctly, so there's less excuse for skipping the reduced-motion fallback." },
    { question: "Do I need to rebuild my existing website to start using these features, or can a developer add them incrementally?", answer: "No rebuild is needed for any of these four. Each one is additive: a growing textarea, an automatic contrast fix, a native accordion style, or a smoother modal fade-in can all be added to an existing page's CSS without touching the surrounding markup, layout, or JavaScript logic that already works. The realistic path is incremental — a developer identifies a handful of components where one of these features removes real complexity (a form, a modal, an FAQ block) and updates those specific pieces during ordinary maintenance work, rather than treating this as a reason for a full redesign." },
  ],
  'website-designer-pune-is-17802-accessibility-2026': [
    { question: "Does IS 17802 legally apply to my business if I'm not SEBI-regulated?", answer: "Not directly, in most cases. IS 17802 is currently binding on government bodies, public sector undertakings, banks and other explicitly regulated sectors, and — since the 2025-2026 circular — on SEBI-regulated financial entities specifically. If your business sits outside those categories, there's no direct legal requirement to comply with IS 17802 today. It's still worth treating as the practical benchmark, since it reflects where Indian regulators have set the bar and overlaps heavily with good usability and SEO practice, but you shouldn't be told it's already mandatory for every website in India, because it isn't." },
    { question: "Is IS 17802 different from WCAG, or basically the same thing?", answer: "They're closely aligned rather than identical. WCAG 2.1 AA is the international standard, developed by the World Wide Web Consortium and used worldwide as the reference for accessible digital content. IS 17802 is India's own Bureau of Indian Standards publication, built on that same WCAG 2.1 AA foundation and intended to work alongside India-specific frameworks like the Guidelines for Indian Government Websites and the RPwD Act. In practice, a site built to WCAG 2.1 AA standards will satisfy the bulk of what IS 17802 asks for, since the underlying success criteria are the same set of testable rules." },
    { question: "What happens if a SEBI-regulated entity misses the compliance deadlines?", answer: "The circular lays out a defined sequence of deadlines running from the September 2025 platform inventory through the final compliance report due 30 April 2027, with audits, remediation, and reporting obligations at each stage. Missing a milestone puts an entity out of step with a regulatory circular from its own market regulator, which is the kind of gap SEBI-regulated firms generally treat seriously given their existing compliance relationship with the regulator. The specific penalties or enforcement mechanics for non-compliance sit with SEBI's own regulatory processes, so any entity in scope should confirm current obligations directly with their compliance team or auditor rather than relying on a general summary." },
    { question: "Can an existing WordPress or custom-coded website be retrofitted for WCAG 2.1 AA / IS 17802, or does it need a full rebuild?", answer: "Retrofitting is usually possible and is what most organisations actually do, rather than rebuilding from scratch. The practical difficulty depends on how the existing site was built: a WordPress site using a well-structured, actively maintained theme and standard blocks can often reach a large share of WCAG 2.1 AA compliance through targeted fixes — contrast adjustments, alt text, form labelling, focus styles — without touching the underlying architecture. A custom-coded site with deeply nested custom components, especially interactive widgets like carousels, tabbed panels, or custom dropdowns built without accessibility in mind, tends to need more substantial component-level rework, because keyboard and screen-reader behaviour for custom interactive elements has to be coded deliberately rather than inherited from standard HTML. Either way, an audit before you start tells you which of those two situations you're actually in." },
    { question: "Does this standard also cover PDFs and videos on a website, or just the web pages themselves?", answer: "It covers more than the HTML pages. The SEBI circular explicitly lists disclosures, documents, and multimedia content alongside websites, apps, and portals as being in scope, and WCAG 2.1 AA more broadly expects that downloadable documents and embedded media meet the same accessibility bar as the page hosting them — meaning PDFs need proper tagging and reading order for screen readers, and videos need captions (with transcripts for audio-only content). A site that passes an accessibility check on its HTML pages but hosts untagged PDF brochures or uncaptioned video content hasn't actually met the standard; both need to be included in any real audit." },
  ],
  'digital-marketing-agency-pune-meta-placement-value-rules-2026': [
    { question: "Did Meta officially announce that placement exclusions were removed?", answer: "No. As of this writing, Meta has not published an official announcement specifically confirming the removal of ad-set-level placement exclusion checkboxes. What exists is a consistent pattern of reports from advertisers who noticed the checkboxes disappearing from their own accounts around 25 August 2026, documented independently by several ad-tech publications. It is accurate to describe this as widely reported and documented rather than as a confirmed Meta policy statement, and any digital marketing agency in Pune advising clients on this should be equally careful with that distinction." },
    { question: "Can I still fully block a specific placement, like Facebook Audience Network, from showing my ads?", answer: "Not at the ad-set level anymore -- that option has been replaced by value rules, which apply a bid discount (as steep as -90%) rather than a true block. You can still block a placement more reliably by using the account-level Brand Safety & Suitability settings in Business Settings, which apply across all campaigns in the account, including automated Advantage+ campaigns, and are not subject to the same discount-not-block behaviour." },
    { question: "What happens to campaigns that already had placement exclusions set before this change?", answer: "Based on advertiser reports, existing ad-set-level exclusions were not deleted outright but were converted into value rules with a heavy negative bid adjustment on the previously excluded placement. In practice this means an exclusion set up months ago may now function as a steep discount rather than a hard block, without any change visible in the campaign name or obvious settings, which is exactly why an account audit is worth doing rather than assuming old settings still behave the way they did when you created them." },
    { question: "Is this the same thing as the Advantage+ campaign changes from February 2026?", answer: "They are related but distinct. The February 2026 unified Advantage+ campaign structure prohibited placement exclusions at the campaign level as part of merging manual and Advantage+ campaign flows into one automated-by-default structure. The August 2026 change removed the separate, ad-set-level exclusion checkbox that had still existed underneath that structure. Together, the two changes mean manual placement exclusion no longer exists as a real option at either the campaign or the ad-set level, leaving only the account-level Brand Safety & Suitability setting as a genuine block." },
    { question: "How do I actually set an account-level placement exclusion instead of an ad-set-level one?", answer: "In Meta Ads Manager, go to Business Settings and locate the Brand Safety & Suitability (or Inventory Filter / Placement Controls) section at the ad-account level, not inside an individual campaign or ad set. Select the placement categories or content types you want to exclude and apply the setting there. Because it sits at the account level, it applies across every campaign in that account, including ones built through fully automated Advantage+ placement flows, and it does not carry the same bid-discount behaviour that ad-set-level value rules do, which is why ad-tech sources currently document it as the more reliable option." },
  ],
  'ecommerce-website-development-pune-woocommerce-hpos-2026': [
    { question: "Do I need to do anything if I'm setting up a brand-new WooCommerce store today?", answer: "For a genuinely new store with no legacy data and no old custom plugins, there is little to actively do — new WooCommerce installations already default to HPOS, so you're starting on the fast, modern storage model from day one. The one thing worth doing regardless is running the built-in compatibility checker in WooCommerce → Settings → Advanced → Features before you install any third-party plugins beyond WooCommerce's own extensions, so you catch an incompatible choice before it's handling live orders rather than after." },
    { question: "How do I check whether my existing store is already running on HPOS or still on the legacy storage?", answer: "Open WooCommerce → Settings → Advanced → Features in your wp-admin dashboard. That screen states directly which storage mode is currently authoritative for your orders and whether the legacy tables are still being kept in sync alongside it. If your store predates late 2023 and nobody has explicitly migrated it, there's a real chance it's still on the old postmeta-based model, and this settings page is the fastest way to confirm one way or the other without digging into the database directly." },
    { question: "What exactly is \"sync-on-read\" and why does WooCommerce 10.7 turning it off by default matter?", answer: "Sync-on-read was a background safety mechanism: if a plugin wrote order data to the old wp_postmeta table instead of the newer HPOS tables, WooCommerce would automatically detect and copy that data into HPOS the next time the order was viewed, quietly fixing the mismatch. WooCommerce 10.7, released in April 2026, turned this off by default. Now, if outdated code still writes to the legacy table, that data simply doesn't make it into the order record WooCommerce actually uses — with no error or warning shown anywhere, which is what makes this change worth taking seriously even if you never touch a settings screen yourself." },
    { question: "Will my existing plugins definitely break under HPOS?", answer: "Not necessarily, and for most stores running actively maintained plugins built to WooCommerce's current standards, nothing changes at all — those plugins already use WooCommerce's official APIs, which work correctly regardless of the underlying storage mode. The real risk is concentrated in older, abandoned, or custom-built code — think a loyalty plugin nobody has updated in years, a bespoke payment integration, or an in-house export script — that writes directly to the old database tables. Running WooCommerce's built-in compatibility checker tells you which specific plugins on your site fall into that risk category, rather than leaving it a guess." },
    { question: "If something goes wrong after migrating to HPOS, can I roll back to the legacy order storage?", answer: "Yes, within a window. WooCommerce's migration process keeps the old legacy tables intact and in sync for a period after you switch to HPOS rather than deleting them immediately, which lets you switch the authoritative storage back to the legacy tables from the same Features settings screen if you notice problems. The important caveat is timing — that rollback option depends on the legacy data still being there, so it's worth watching order behavior closely in the days right after migration rather than assuming everything is fine and moving on." },
  ],
  'web-development-company-pune-wordpress-6-9-2026': [
    { question: "Is WordPress 6.9 safe to install on a live business website?", answer: "Not directly on a live site. Test it on a staging copy first, since custom blocks, older page builders, and unmaintained plugins can behave unpredictably on a major release. Once staging confirms your theme, plugins, and custom blocks work, the upgrade itself is routine." },
    { question: "Do I need a developer to use the new Accordion, Math, Time to Read, or Word Count blocks?", answer: "No — these are native blocks available to any editor through the block inserter, the same as a paragraph or image block. A developer is only needed if you want custom styling beyond what the block settings panel offers." },
    { question: "What is the Abilities API and does it affect my website if I'm not using AI tools?", answer: "The Abilities API lets plugins expose specific, well-defined actions that AI agents and automation tools can call safely, rather than an AI acting on your site through guesswork. If you're not using AI tooling on your site today, it has no visible effect — it matters once a plugin you use starts offering AI-assisted features built on it." },
    { question: "Will WordPress 6.9 break my page builder or custom theme?", answer: "It can, if the page builder or theme was built against an older version of the Block API and hasn't been updated for 6.9's changes. Check your page builder vendor's changelog for 6.9 compatibility before upgrading, and always confirm in staging rather than assuming compatibility." },
    { question: "How much does it typically cost to fix a WordPress 6.9 compatibility issue?", answer: "For most sites this is a few hours of a developer's time to test and patch a broken custom block or plugin conflict, not a rebuild. Sites running heavily customized page builders or old bespoke block code can take longer — get a specific quote after a staging diagnosis rather than assuming a fixed cost." },
  ],
  'digital-marketing-agency-pune-ai-ad-disclosure-2026': [
    { question: "Does using AI to write my ad copy require disclosure on Meta?", answer: "Generally no. Meta's AI info labeling is aimed at photorealistic AI-generated or AI-edited images, video, and audio, not AI-assisted text or copywriting. If your AI use is limited to drafting ad copy, it typically won't trigger the label." },
    { question: "Will my ad get rejected if it carries the \"AI info\" label?", answer: "Not on its own. The label is a transparency disclosure, not a policy violation, and plenty of compliant ads carry it. Rejection is more likely if the underlying creative itself violates a separate policy, such as a health claim or a misleading before-and-after image." },
    { question: "How do I know if my AI-generated image will trigger the C2PA detection?", answer: "If the image was created or edited with a generative AI tool that embeds C2PA content-credential metadata — increasingly the default in mainstream AI image and video tools — Meta's detection can pick it up automatically. If you're unsure, treat any AI-touched photorealistic visual as likely to be labeled and plan your creative review accordingly." },
    { question: "Is this the same as Meta's Advantage+ automated ad tools?", answer: "No. Advantage+ is about campaign automation — bidding, targeting, and creative optimization. The AI info label is a separate transparency requirement about the content itself, and applies whether or not you're using Advantage+." },
    { question: "Does this apply retroactively to ads I already ran earlier in 2026?", answer: "Meta's detection and labeling apply going forward to ads as they are served and reviewed, and the rollout for third-party AI detection has been gradual since its June 2026 expansion. Don't assume every older AI-touched ad in your account has been labeled — review upcoming and active campaigns rather than relying on past approval as a signal." },
  ],
  'ecommerce-website-development-pune-merchant-api-migration-2026': [
    { question: "My store uses a Google Sheets feed to Merchant Center. Do I need to do anything?", answer: "No — the Content API sunset only affects programmatic, API-based integrations. Manual file uploads, scheduled URL fetches, and Google Sheets feeds continued working through and after the 18 August 2026 cutover without any action needed." },
    { question: "How do I know if my Shopify store was affected?", answer: "If you use Shopify's native Google & YouTube channel app or a feed app that syncs automatically via API, check that app's changelog or support page for a Merchant API migration notice. If your feed updates only through manual CSV upload or a scheduled file fetch, you weren't directly affected." },
    { question: "What is the fastest way to check if my current Shopping listings are stale?", answer: "Open the Diagnostics tab in Google Merchant Center and look for a spike in disapproved items, a stopped 'last updated' timestamp on your data source, or items marked out of stock that still show as purchasable on your live site — any of these point to a feed that stopped syncing." },
    { question: "Is the out-of-stock buy button issue something Google warns about first, or does it suspend accounts immediately?", answer: "Google's stated policy treats an active buy button on a genuinely out-of-stock page as a misrepresentation issue, which is a more serious classification than a routine item disapproval and can lead to account-level enforcement rather than just that one listing being pulled. Fix stale inventory data before it's flagged rather than waiting for an enforcement notice." },
    { question: "Does the September 2026 policy consolidation change what I need to comply with?", answer: "No — Google has described it as merging the separate Shopping ads and free-listings help-center pages into one organized policy set, not introducing new restrictions or stricter enforcement. Existing compliant feeds don't need new changes because of this specific update." },
  ],
  'ngo-website-development-india-whatsapp-business-agent-2026': [
    { question: "Does Meta's WhatsApp Business AI agent cost extra to enable?", answer: "Meta has not published NGO-specific pricing, and this article isn't the place to guess at commercial terms that can change. Confirm current costs directly with Meta or your WhatsApp Business Solution Provider before committing to a rollout." },
    { question: "Can the AI agent send donation receipts or 80G certificates directly?", answer: "Technically a connected system could trigger that message, but issuing a compliance-sensitive document like an 80G receipt should stay on a verified, scripted workflow tied to your actual donation and receipt-numbering records, not open-ended AI generation. Treat the AI agent as a front door for questions, not the system of record for compliance documents." },
    { question: "Do we need a new WhatsApp Business API integration to use this, or does our existing one qualify?", answer: "Most NGOs already running WhatsApp Business API for donor communication have the underlying infrastructure — verified number, Cloud API access, approved templates — that this builds on. Confirm with your WhatsApp Business Solution Provider whether Meta Business Agent is available on your current setup or requires a configuration change." },
    { question: "Is Meta's AI agent aware of Indian FCRA and 80G rules specifically?", answer: "There's no published evidence that Meta has trained or configured the agent with India-specific nonprofit tax and compliance rules. Treat any answer it gives on FCRA, 80G, or tax-deduction specifics as unverified, and route those questions to a human or a pre-written scripted reply instead." },
    { question: "How is this different from the chatbot flows NGOs already run on WhatsApp?", answer: "A scripted WhatsApp flow follows a fixed decision tree you built and can fully audit. Meta's AI agent generates open-ended responses, which is more flexible for donor FAQs but harder to guarantee will never say something wrong — that trade-off is the core decision this article walks through." },
  ],
};

export const BLOG_FAQ_SCHEMA: Record<string, ReturnType<typeof createFAQSchema>> =
  Object.fromEntries(Object.entries(BLOG_FAQ).map(([id, faqs]) => [id, createFAQSchema(faqs)]));
