// FAQPage JSON-LD for blog posts that include a visible "Frequently Asked
// Questions" section. Keyed by blog id; the Q&A text here must match what
// renders on the page — this is a schema mirror, not separate content.
import { createFAQSchema } from './schema';

export const BLOG_FAQ: Record<string, { question: string; answer: string }[]> = {
  'web-development-company-pune-wordpress-6-9-2026': [
    { question: "Is WordPress 6.9 safe to install on a live business website?", answer: "Not directly on a live site. Test it on a staging copy first, since custom blocks, older page builders, and unmaintained plugins can behave unpredictably on a major release. Once staging confirms your theme, plugins, and custom blocks work, the upgrade itself is routine." },
    { question: "Do I need a developer to use the new Accordion, Math, Time to Read, or Word Count blocks?", answer: "No — these are native blocks available to any editor through the block inserter, the same as a paragraph or image block. A developer is only needed if you want custom styling beyond what the block settings panel offers." },
    { question: "What is the Abilities API and does it affect my website if I'm not using AI tools?", answer: "The Abilities API lets plugins expose specific, well-defined actions that AI agents and automation tools can call safely, rather than an AI acting on your site through guesswork. If you're not using AI tooling on your site today, it has no visible effect — it matters once a plugin you use starts offering AI-assisted features built on it." },
    { question: "Will WordPress 6.9 break my page builder or custom theme?", answer: "It can, if the page builder or theme was built against an older version of the Block API and hasn't been updated for 6.9's changes. Check your page builder vendor's changelog for 6.9 compatibility before upgrading, and always confirm in staging rather than assuming compatibility." },
    { question: "How much does it typically cost to fix a WordPress 6.9 compatibility issue?", answer: "For most sites this is a few hours of a developer's time to test and patch a broken custom block or plugin conflict, not a rebuild. Sites running heavily customized page builders or old bespoke block code can take longer — get a specific quote after a staging diagnosis rather than assuming a fixed cost." },
  ],
  'digital-marketing-agency-pune-ai-ad-disclosure-2026': [
    { question: "Does using AI to write my ad copy require disclosure on Meta?", answer: "Generally no. Meta's AI info labeling is aimed at photorealistic AI-generated or AI-edited images, video, and audio, not AI-assisted text or copywriting. If your AI use is limited to drafting ad copy, it typically won't trigger the label." },
    { question: "Will my ad get rejected if it carries the \"AI info\" label?", answer: "Not on its own. The label is a transparency disclosure, not a policy violation, and plenty of compliant ads carry it. Rejection is more likely if the underlying creative itself violates a separate policy, such as a health claim or a misleading before-and-after image." },
    { question: "How do I know if my AI-generated image will trigger the C2PA detection?", answer: "If the image was created or edited with a generative AI tool that embeds C2PA content-credential metadata — increasingly the default in mainstream AI image and video tools — Meta's detection can pick it up automatically. If you're unsure, treat any AI-touched photorealistic visual as likely to be labeled and plan your creative review accordingly." },
    { question: "Is this the same as Meta's Advantage+ automated ad tools?", answer: "No. Advantage+ is about campaign automation — bidding, targeting, and creative optimization. The AI info label is a separate transparency requirement about the content itself, and applies whether or not you're using Advantage+." },
    { question: "Does this apply retroactively to ads I already ran earlier in 2026?", answer: "Meta's detection and labeling apply going forward to ads as they are served and reviewed, and the rollout for third-party AI detection has been gradual since its June 2026 expansion. Don't assume every older AI-touched ad in your account has been labeled — review upcoming and active campaigns rather than relying on past approval as a signal." },
  ],
  'ecommerce-website-development-pune-merchant-api-migration-2026': [
    { question: "My store uses a Google Sheets feed to Merchant Center. Do I need to do anything?", answer: "No — the Content API sunset only affects programmatic, API-based integrations. Manual file uploads, scheduled URL fetches, and Google Sheets feeds continued working through and after the 18 August 2026 cutover without any action needed." },
    { question: "How do I know if my Shopify store was affected?", answer: "If you use Shopify's native Google & YouTube channel app or a feed app that syncs automatically via API, check that app's changelog or support page for a Merchant API migration notice. If your feed updates only through manual CSV upload or a scheduled file fetch, you weren't directly affected." },
    { question: "What is the fastest way to check if my current Shopping listings are stale?", answer: "Open the Diagnostics tab in Google Merchant Center and look for a spike in disapproved items, a stopped 'last updated' timestamp on your data source, or items marked out of stock that still show as purchasable on your live site — any of these point to a feed that stopped syncing." },
    { question: "Is the out-of-stock buy button issue something Google warns about first, or does it suspend accounts immediately?", answer: "Google's stated policy treats an active buy button on a genuinely out-of-stock page as a misrepresentation issue, which is a more serious classification than a routine item disapproval and can lead to account-level enforcement rather than just that one listing being pulled. Fix stale inventory data before it's flagged rather than waiting for an enforcement notice." },
    { question: "Does the September 2026 policy consolidation change what I need to comply with?", answer: "No — Google has described it as merging the separate Shopping ads and free-listings help-center pages into one organized policy set, not introducing new restrictions or stricter enforcement. Existing compliant feeds don't need new changes because of this specific update." },
  ],
  'ngo-website-development-india-whatsapp-business-agent-2026': [
    { question: "Does Meta's WhatsApp Business AI agent cost extra to enable?", answer: "Meta has not published NGO-specific pricing, and this article isn't the place to guess at commercial terms that can change. Confirm current costs directly with Meta or your WhatsApp Business Solution Provider before committing to a rollout." },
    { question: "Can the AI agent send donation receipts or 80G certificates directly?", answer: "Technically a connected system could trigger that message, but issuing a compliance-sensitive document like an 80G receipt should stay on a verified, scripted workflow tied to your actual donation and receipt-numbering records, not open-ended AI generation. Treat the AI agent as a front door for questions, not the system of record for compliance documents." },
    { question: "Do we need a new WhatsApp Business API integration to use this, or does our existing one qualify?", answer: "Most NGOs already running WhatsApp Business API for donor communication have the underlying infrastructure — verified number, Cloud API access, approved templates — that this builds on. Confirm with your WhatsApp Business Solution Provider whether Meta Business Agent is available on your current setup or requires a configuration change." },
    { question: "Is Meta's AI agent aware of Indian FCRA and 80G rules specifically?", answer: "There's no published evidence that Meta has trained or configured the agent with India-specific nonprofit tax and compliance rules. Treat any answer it gives on FCRA, 80G, or tax-deduction specifics as unverified, and route those questions to a human or a pre-written scripted reply instead." },
    { question: "How is this different from the chatbot flows NGOs already run on WhatsApp?", answer: "A scripted WhatsApp flow follows a fixed decision tree you built and can fully audit. Meta's AI agent generates open-ended responses, which is more flexible for donor FAQs but harder to guarantee will never say something wrong — that trade-off is the core decision this article walks through." },
  ],
};

export const BLOG_FAQ_SCHEMA: Record<string, ReturnType<typeof createFAQSchema>> =
  Object.fromEntries(Object.entries(BLOG_FAQ).map(([id, faqs]) => [id, createFAQSchema(faqs)]));
