#!/usr/bin/env python3
"""
Generate src/seo/blogFaq.ts from the visible "Frequently Asked Questions"
section of every article in public/blog-data/*.json.

Google requires FAQPage structured data to MIRROR a visible FAQ section on the
page — it is not separate content. So the single source of truth is the article
body itself: this script reads the markdown, lifts each `### question` and its
answer out of the `## Frequently Asked Questions` block, and emits a matching
schema map. Run it whenever articles change (alongside gen_blog_meta.py); never
hand-edit blogFaq.ts.
"""
import json, re, glob, pathlib

SITE = "https://govindaniit.com"
DATA = "public/blog-data"
OUT  = "src/seo/blogFaq.ts"

# Markdown link [text](url) -> Google-allowed <a href> with an absolute URL.
LINK = re.compile(r'\[([^\]]+)\]\((\S+?)\)')
def _abs(u: str) -> str:
    if u.startswith("http"): return u
    if u.startswith("/"):    return SITE + u
    return u

def clean(md: str) -> str:
    t = md.strip()
    t = LINK.sub(lambda m: f'<a href="{_abs(m.group(2))}">{m.group(1)}</a>', t)
    t = re.sub(r'\*\*(.+?)\*\*', r'\1', t)          # bold
    t = re.sub(r'(?<!\*)\*(?!\*)(.+?)\*', r'\1', t) # italic
    t = re.sub(r'^\s*[-*]\s+', '', t, flags=re.M)   # list bullets
    t = re.sub(r'`([^`]+)`', r'\1', t)              # inline code
    t = re.sub(r'\s+', ' ', t).strip()              # collapse whitespace
    return t

def extract(content: str):
    """Return [{question, answer}] from the visible FAQ block, or []."""
    m = re.search(r'^#{2,3}\s+.*(frequently asked questions|faqs?)\b.*$',
                  content, re.I | re.M)
    if not m:
        return []
    seg = content[m.end():]
    nxt = re.search(r'^##\s', seg, re.M)            # FAQ ends at the next H2
    if nxt:
        seg = seg[:nxt.start()]
    questions = re.findall(r'^###\s+(.*)$', seg, re.M)
    answers   = re.split(r'^###\s+.*$', seg, flags=re.M)[1:]
    out = []
    for q, a in zip(questions, answers):
        qq, aa = clean(q), clean(a)
        if qq and aa:
            out.append({"question": qq, "answer": aa})
    return out

def main():
    faqs = {}
    for f in sorted(glob.glob(f"{DATA}/*.json")):
        slug = pathlib.Path(f).stem
        try:
            content = json.load(open(f)).get("content", "") or ""
        except Exception:
            continue
        items = extract(content)
        if items:
            faqs[slug] = items

    lines = [
        "// GENERATED by tools/seo/gen_blog_faq.py — do not edit by hand.",
        "// FAQPage JSON-LD for blog posts, mirrored from the visible",
        "// \"Frequently Asked Questions\" section of each article.",
        "import { createFAQSchema } from './schema';",
        "",
        "export const BLOG_FAQ: Record<string, { question: string; answer: string }[]> = {",
    ]
    for slug, items in faqs.items():
        lines.append(f"  {json.dumps(slug)}: [")
        for it in items:
            lines.append(
                f"    {{ question: {json.dumps(it['question'], ensure_ascii=False)}, "
                f"answer: {json.dumps(it['answer'], ensure_ascii=False)} }},"
            )
        lines.append("  ],")
    lines += [
        "};",
        "",
        "export const BLOG_FAQ_SCHEMA: Record<string, ReturnType<typeof createFAQSchema>> =",
        "  Object.fromEntries(Object.entries(BLOG_FAQ).map(([id, f]) => [id, createFAQSchema(f)]));",
        "",
    ]
    pathlib.Path(OUT).write_text("\n".join(lines))
    total = sum(len(v) for v in faqs.values())
    print(f"  {len(faqs)} posts with FAQs, {total} Q&A pairs -> {OUT}")

if __name__ == "__main__":
    main()
