#!/usr/bin/env python3
"""Build a light id -> {title, excerpt} map for blog routes.

Seo.tsx cannot import blogs.ts: it is 931 KB of article bodies and would land in
the main bundle on every page. This extracts only the two fields the <head>
needs, so blog posts stop falling through to the site-wide default description.
"""
import json, pathlib, re

src = pathlib.Path("src/data/blogs.ts").read_text()
# records start at `id: "…"` and carry title/excerpt before `content:`
recs = []
for m in re.finditer(r'\bid:\s*"([^"]+)"', src):
    start = m.end()
    window = src[start:start + 4000]
    t = re.search(r'\btitle:\s*"((?:[^"\\]|\\.)*)"', window)
    e = re.search(r'\bexcerpt:\s*"((?:[^"\\]|\\.)*)"', window)
    d = re.search(r'\bdate:\s*"([^"]+)"', window)
    if t and e:
        unesc = lambda s: s.replace('\\"', '"').replace("\\'", "'")
        recs.append({"id": m.group(1), "title": unesc(t.group(1)),
                     "excerpt": unesc(e.group(1)), "date": d.group(1) if d else ""})

seen, out = set(), []
for r in recs:
    if r["id"] in seen:
        continue
    seen.add(r["id"]); out.append(r)

lines = ["// GENERATED by tools/seo/gen_blog_meta.py — do not edit by hand.",
         "// Blog <head> data only. blogs.ts itself is 931 KB and must never be",
         "// imported by the SEO layer, which loads on every route.",
         "export type BlogMeta = { title: string; description: string; date: string };",
         "export const BLOG_META: Record<string, BlogMeta> = {"]
for r in out:
    esc = lambda s: s.replace("\\", "\\\\").replace("'", "\\'")
    # meta descriptions are truncated by search engines past ~160 chars
    desc = r["excerpt"]
    if len(desc) > 158:
        cut = desc[:158].rsplit(" ", 1)[0].rstrip(",;:-—– ")
        desc = cut + "…"
    lines.append(f"  '{esc(r['id'])}': {{ title: '{esc(r['title'])}', "
                 f"description: '{esc(desc)}', date: '{r['date']}' }},")
lines.append("};")
pathlib.Path("src/seo/blogMeta.ts").write_text("\n".join(lines) + "\n")
print(f"  {len(out)} blog posts -> src/seo/blogMeta.ts")
long_t = [r for r in out if len(r["title"]) > 60]
print(f"  titles over 60 chars: {len(long_t)}")
