#!/usr/bin/env python3
"""Submit URLs to IndexNow only after they are provably live.

Why this exists: on 2026-09-27 four blog slugs were submitted to IndexNow the
moment they were WRITTEN, while their pages were dated 2026-12-17/18 and
therefore 404. Search engines were handed dead URLs. Submitting a 404 is worse
than submitting nothing: it spends crawl budget and teaches the engine that our
IndexNow feed is unreliable.

The rule this enforces is simple and has no exceptions:

    a URL is submitted only after a live GET of that exact URL returns 200.

It is also stateless. "What is new" is the difference between the sitemap the
server was serving BEFORE this deploy and the one it serves AFTER — both are
generated by tools/seo/gen_sitemap.py from prerendered output, so a URL can
only appear there if a page really was built for it.

Usage (see .github/workflows/deploy.yml):
    # before rsync
    curl -sf https://govindaniit.com/sitemap.xml -o /tmp/sitemap-before.xml || :
    # after rsync + blog mirror
    python3 tools/seo/indexnow_ping.py \
        --before /tmp/sitemap-before.xml --after dist/sitemap.xml --submit
"""
import argparse, json, pathlib, re, sys, time, urllib.error, urllib.request

ROOT = pathlib.Path(__file__).resolve().parents[2]
SITE = "https://govindaniit.com"
HOST = "govindaniit.com"
ENDPOINT = "https://api.indexnow.org/indexnow"
# IndexNow accepts at most 10,000 URLs per request; we cap far lower so a
# runaway diff can never blast the whole site at the engines.
MAX_SUBMIT = 200
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 GovindaniIndexNow/1.0")


def find_key():
    """The key file already lives in public/ and is served at the site root."""
    for f in (ROOT / "public").glob("*.txt"):
        if re.fullmatch(r"[0-9a-f]{32}", f.stem) and f.read_text().strip() == f.stem:
            return f.stem
    sys.exit("indexnow: no <32-hex>.txt key file in public/")


def locs(path):
    p = pathlib.Path(path)
    if not p.exists() or not p.stat().st_size:
        return set()
    return set(re.findall(r"<loc>\s*([^<\s]+)\s*</loc>", p.read_text(errors="replace")))


def live_200(url, attempts=3, pause=5):
    """rsync has just finished and LiteSpeed may still be serving a cached 404,
    so a miss is retried before the URL is discarded."""
    for i in range(attempts):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": UA})
            with urllib.request.urlopen(req, timeout=45) as r:
                if r.status == 200:
                    return True, 200
                last = r.status
        except urllib.error.HTTPError as e:
            last = e.code
        except Exception as e:
            last = str(e)[:60]
        if i < attempts - 1:
            time.sleep(pause)
    return False, last


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--before", required=True, help="sitemap.xml as served BEFORE this deploy")
    ap.add_argument("--after", required=True, help="sitemap.xml produced by THIS build")
    ap.add_argument("--submit", action="store_true",
                    help="actually POST to IndexNow (otherwise dry run)")
    ap.add_argument("--max", type=int, default=MAX_SUBMIT)
    a = ap.parse_args()

    before, after = locs(a.before), locs(a.after)
    if not after:
        sys.exit("indexnow: --after sitemap is empty or missing; refusing to run")
    added = sorted(after - before)
    removed = sorted(before - after)

    print(f"  sitemap before: {len(before)} URLs")
    print(f"  sitemap after:  {len(after)} URLs")
    print(f"  newly present:  {len(added)}")
    print(f"  disappeared:    {len(removed)}")
    for u in removed[:10]:
        print(f"    gone: {u}")

    if not before:
        # No baseline (first run, or the live sitemap was unreachable). Diffing
        # against nothing would submit the entire site as "new", so we stop.
        print("  no usable baseline — skipping submission this run")
        return 0
    if not added:
        print("  nothing new to submit")
        return 0

    verified, rejected = [], []
    for u in added[:a.max]:
        ok, code = live_200(u)
        (verified if ok else rejected).append((u, code))
        print(f"    {'200 OK ' if ok else 'SKIP   '} {u}" + ("" if ok else f"  (got {code})"))

    if rejected:
        print(f"::warning::{len(rejected)} URL(s) are in the new sitemap but did "
              f"not return 200 live; they were NOT submitted to IndexNow")

    if not verified:
        print("  nothing verified live — submitting nothing")
        return 0

    payload = {"host": HOST, "key": find_key(),
               "keyLocation": f"{SITE}/{find_key()}.txt",
               "urlList": [u for u, _ in verified]}

    if not a.submit:
        print(f"  DRY RUN — would submit {len(payload['urlList'])} verified URL(s)")
        return 0

    req = urllib.request.Request(
        ENDPOINT, data=json.dumps(payload).encode(), method="POST",
        headers={"Content-Type": "application/json; charset=utf-8", "User-Agent": UA})
    try:
        with urllib.request.urlopen(req, timeout=60) as r:
            print(f"  IndexNow: HTTP {r.status} for {len(payload['urlList'])} URL(s)")
    except urllib.error.HTTPError as e:
        # A failed ping must never fail the deploy — the site is already live.
        print(f"::warning::IndexNow returned HTTP {e.code}: {e.read()[:200]!r}")
    except Exception as e:
        print(f"::warning::IndexNow submission failed: {str(e)[:200]}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
